### ISSUE TITLE
[Trace Agent] Step order is incorrect

### ISSUE THREAD

**Issue by lylytran** [llmhyy/microbat#163]
Stack trace: 
java.lang.ArrayIndexOutOfBoundsException: -1
working on the 8th bug of Closure project.
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at microbat.instrumentation.output.TraceOutputReader.readNode(TraceOutputReader.java:178)
	at microbat.instrumentation.output.TraceOutputReader.readSteps(TraceOutputReader.java:119)
	at microbat.instrumentation.output.TraceOutputReader.readTrace(TraceOutputReader.java:47)
	at microbat.instrumentation.output.RunningInfo.readFromFile(RunningInfo.java:41)
	at microbat.agent.TraceAgentRunner.runWithDumpFileOption(TraceAgentRunner.java:108)
	at microbat.codeanalysis.runtime.InstrumentationExecutor.execute(InstrumentationExecutor.java:164)
	at microbat.codeanalysis.runtime.InstrumentationExecutor.run(InstrumentationExecutor.java:122)
	at traceagent.handler.RunAllDefects4jHandler.run(RunAllDefects4jHandler.java:142)
	at traceagent.handler.RunAllDefects4jHandler.runSingleBug(RunAllDefects4jHandler.java:119)
	at traceagent.handler.RunAllDefects4jHandler.runAll(RunAllDefects4jHandler.java:92)
	at traceagent.handler.RunAllDefects4jHandler$1.run(RunAllDefects4jHandler.java:53)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Cmd:
Trace dumpfile: E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\trace\Closure\7\bug.exec
E:\lyly\Projects\microbat\jdk\jdk1.7.0_80\bin\java -Xmx30g -ea -noverify -javaagent:E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\instrumentator.jar=precheck=false,java_home=E:\lyly\Projects\microbat\jdk\jdk1.7.0_80,stepLimit=100000,log=printProgress;info,require_method_split=false,working_dir=E:\linyun\bug_repo\Closure\7\bug,varLayer=2,launch_class=com.google.javascript.jscomp.ClosureReverseAbstractInterpreterTest,class_path=E:\linyun\bug_repo\Closure\7\bug\build\test;E:\linyun\bug_repo\Closure\7\bug\build\classes;E:\linyun\bug_repo\Closure\7\bug\lib\ant-launcher.jar;E:\linyun\bug_repo\Closure\7\bug\lib\ant.jar;E:\linyun\bug_repo\Closure\7\bug\lib\args4j.jar;E:\linyun\bug_repo\Closure\7\bug\lib\caja-r4314.jar;E:\linyun\bug_repo\Closure\7\bug\lib\guava.jar;E:\linyun\bug_repo\Closure\7\bug\lib\jarjar.jar;E:\linyun\bug_repo\Closure\7\bug\lib\json.jar;E:\linyun\bug_repo\Closure\7\bug\lib\jsr305.jar;E:\linyun\bug_repo\Closure\7\bug\lib\junit.jar;E:\linyun\bug_repo\Closure\7\bug\lib\protobuf-java.jar;E:\linyun\bug_repo\Closure\7\bug\lib\rhino\testsrc\org\mozilla\javascript\tests\commonjs\module\modules.jar;E:\linyun\bug_repo\Closure\7\bug\build\lib\rhino.jar;E:\linyun\bug_repo\Closure\7\bug\build\lib\rhino1_7R4pre\js.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\junit.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\org.hamcrest.core.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\testrunner.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\bcel-6.0.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\javassist.jar,dump_file_path=E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\trace\Closure\7\bug.exec,expectedSteps=60837 -cp E:\linyun\bug_repo\Closure\7\bug\build\test;E:\linyun\bug_repo\Closure\7\bug\build\classes;E:\linyun\bug_repo\Closure\7\bug\lib\ant-launcher.jar;E:\linyun\bug_repo\Closure\7\bug\lib\ant.jar;E:\linyun\bug_repo\Closure\7\bug\lib\args4j.jar;E:\linyun\bug_repo\Closure\7\bug\lib\caja-r4314.jar;E:\linyun\bug_repo\Closure\7\bug\lib\guava.jar;E:\linyun\bug_repo\Closure\7\bug\lib\jarjar.jar;E:\linyun\bug_repo\Closure\7\bug\lib\json.jar;E:\linyun\bug_repo\Closure\7\bug\lib\jsr305.jar;E:\linyun\bug_repo\Closure\7\bug\lib\junit.jar;E:\linyun\bug_repo\Closure\7\bug\lib\protobuf-java.jar;E:\linyun\bug_repo\Closure\7\bug\lib\rhino\testsrc\org\mozilla\javascript\tests\commonjs\module\modules.jar;E:\linyun\bug_repo\Closure\7\bug\build\lib\rhino.jar;E:\linyun\bug_repo\Closure\7\bug\build\lib\rhino1_7R4pre\js.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\junit.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\org.hamcrest.core.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\testrunner.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\bcel-6.0.jar;E:\lyly\eclipse-java-mars-clean\eclipse-for-unmodified-code\dropins\junit_lib\javassist.jar microbat.evaluation.junit.MicroBatTestRunner com.google.javascript.jscomp.ClosureReverseAbstractInterpreterTest testGoogIsFunction2

**Comment by lylytran** [comment]
fixed at rev.cef7b9cab4b791f9ed680042e24335935b925bb9 [cef7b9c]
