### ISSUE TITLE
[Trace File] Mockito-6 Reprot EOFException

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#171]
hi @lylytran 

Would you please help check mockito-6-org.mockitousage.matchers.AnyXMatchersAcceptNullsTest::shouldNotAcceptNullInAllAnyPrimitiveWrapperMatchers, the exception is as follows:

```

java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at microbat.instrumentation.output.TraceOutputReader.readVarInt(TraceOutputReader.java:265)
	at microbat.instrumentation.output.TraceOutputReader.readSerializableList(TraceOutputReader.java:150)
	at microbat.instrumentation.output.TraceOutputReader.readRWVarValues(TraceOutputReader.java:137)
	at microbat.instrumentation.output.TraceOutputReader.readSteps(TraceOutputReader.java:125)
	at microbat.instrumentation.output.TraceOutputReader.readTrace(TraceOutputReader.java:47)
	at microbat.instrumentation.output.RunningInfo.readFromFile(RunningInfo.java:41)
	at microbat.agent.TraceAgentRunner.runWithDumpFileOption(TraceAgentRunner.java:110)
	at microbat.codeanalysis.runtime.InstrumentationExecutor.execute(InstrumentationExecutor.java:165)
	at microbat.codeanalysis.runtime.InstrumentationExecutor.run(InstrumentationExecutor.java:123)
	at tregression.separatesnapshots.TraceCollector0.run(TraceCollector0.java:36)
	at tregression.empiricalstudy.TrialGenerator0.analyzeTestCase(TrialGenerator0.java:231)
	at tregression.empiricalstudy.TrialGenerator0.generateTrials(TrialGenerator0.java:88)
	at tregression.handler.SeparateVersionHandler$1.run(SeparateVersionHandler.java:52)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
sav.common.core.SavRtException: java.io.EOFException
	at microbat.instrumentation.output.RunningInfo.readFromFile(RunningInfo.java:45)
	at microbat.agent.TraceAgentRunner.runWithDumpFileOption(TraceAgentRunner.java:110)
	at microbat.codeanalysis.runtime.InstrumentationExecutor.execute(InstrumentationExecutor.java:165)
	at microbat.codeanalysis.runtime.InstrumentationExecutor.run(InstrumentationExecutor.java:123)
	at tregression.separatesnapshots.TraceCollector0.run(TraceCollector0.java:36)
	at tregression.empiricalstudy.TrialGenerator0.analyzeTestCase(TrialGenerator0.java:231)
	at tregression.empiricalstudy.TrialGenerator0.generateTrials(TrialGenerator0.java:88)
	at tregression.handler.SeparateVersionHandler$1.run(SeparateVersionHandler.java:52)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at microbat.instrumentation.output.TraceOutputReader.readVarInt(TraceOutputReader.java:265)
	at microbat.instrumentation.output.TraceOutputReader.readSerializableList(TraceOutputReader.java:150)
	at microbat.instrumentation.output.TraceOutputReader.readRWVarValues(TraceOutputReader.java:137)
	at microbat.instrumentation.output.TraceOutputReader.readSteps(TraceOutputReader.java:125)
	at microbat.instrumentation.output.TraceOutputReader.readTrace(TraceOutputReader.java:47)
	at microbat.instrumentation.output.RunningInfo.readFromFile(RunningInfo.java:41)
	... 8 more
all the trials
```

**Comment by llmhyy** [comment]
same as Time-21-org.joda.time.TestDateTimeZone::testGetName_berlin

**Comment by lylytran** [comment]
To note, for Mockito-6, there are two bugs revealed:
1. Simulator Debugging result changed from "found root cause" to "over_skip".
    correct rev. 098ed5f0b3546a8eba1c95c7b7a5a8df53fc04e6 [098ed5f]
    buggy rev. b44c72a57739ada4e8966a9b510a76828158ccc0 [b44c72a]
2. Agent crash with "java.lang.reflect.Method" added in "includes" option to be instrumented. (hidden bug reveals)

**Comment by llmhyy** [comment]
done
