### ISSUE TITLE
store execution trace into sqlite3 database

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#208]
1. try to modify the trace storage  (check https://github.com/llmhyy/microbat/wiki/Trace-Debugging)
2. sync the generated ddl in the code.

**Comment by llmhyy** [comment]
for translate mysql to sqlite: microbat.sql.SqliteConnectionFactory.transferSql() throws FileNotFoundException

**Comment by llmhyy** [comment]
task 2: follow: https://github.com/llmhyy/microbat/wiki/Trace-Debugging

**Comment by llmhyy** [comment]
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table Run has no column named thread_status)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at microbat.sql.SqliteRecorder.insertRun(SqliteRecorder.java:67)
	at microbat.sql.SqliteRecorder.store(SqliteRecorder.java:48)
	at microbat.instrumentation.TraceAgent.shutdown(TraceAgent.java:74)
	at microbat.instrumentation.Agent.stop(Agent.java:77)
	at microbat.instrumentation.Agent._exitProgram(Agent.java:56)
	at exp.datarace.DataRaces.main(DataRaces.java:13)
|
