### ISSUE TITLE
Null Pointer Exception when precheck step info exceeds step limit

### ISSUE THREAD

**Issue by dingyuchen** [llmhyy/microbat#216]
Long running programs may have steps that exceed the step limit.
Microbat throws a null point exception when such a scenario happens in the precheck stage.

```
java.lang.NullPointerException
	at microbat.codeanalysis.runtime.RunningInformation.<init>(RunningInformation.java:21)
	at microbat.codeanalysis.runtime.InstrumentationExecutor.run(InstrumentationExecutor.java:154)
	at microbat.handler.StartDebugHandler$2.run(StartDebugHandler.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

We may need to look into upgrading `int` type to `long` in the settings menu as well.

**Comment by dingyuchen** [comment]
RunningInformation now throws a more helpful error. step limit may still need to be a `long`
