### ISSUE TITLE
JDI Timeout Issue

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#29]
The correct trace of 4376 steps is to be generated for org.apache.commons.math.util.OpenIntToDoubleHashMapTest#testPutKeysWithCollisions
JVM is started...
progress: ==========10%==========20%==========30%==========40%==========50%==========60%==========70%========
JVM is ended.
org.eclipse.jdi.TimeoutException: Timeout occurred while waiting for packet -1118735817.
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:187)
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:198)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:192)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:243)
	at org.eclipse.jdi.internal.ObjectReferenceImpl.referenceType(ObjectReferenceImpl.java:526)
	at org.eclipse.jdi.internal.ObjectReferenceImpl.type(ObjectReferenceImpl.java:545)
	at microbat.codeanalysis.runtime.variable.VariableValueExtractor.appendClassVarVal(VariableValueExtractor.java:453)
	at microbat.codeanalysis.runtime.variable.VariableValueExtractor.appendVarVal(VariableValueExtractor.java:388)
	at microbat.codeanalysis.runtime.variable.VariableValueExtractor.appendArrVarVal(VariableValueExtractor.java:542)
	at microbat.codeanalysis.runtime.variable.VariableValueExtractor.appendVarVal(VariableValueExtractor.java:362)
	at microbat.codeanalysis.runtime.variable.VariableValueExtractor.appendClassVarVal(VariableValueExtractor.java:454)
	at microbat.codeanalysis.runtime.variable.VariableValueExtractor.appendVarVal(VariableValueExtractor.java:388)
	at microbat.codeanalysis.runtime.variable.VariableValueExtractor.collectValue(VariableValueExtractor.java:222)
	at microbat.codeanalysis.runtime.variable.VariableValueExtractor.extractValue(VariableValueExtractor.java:147)
	at microbat.codeanalysis.runtime.ProgramExecutor.extractValuesAtLocation(ProgramExecutor.java:1343)
	at microbat.codeanalysis.runtime.ProgramExecutor.collectValueOfPreviousStep(ProgramExecutor.java:1311)
	at microbat.codeanalysis.runtime.ProgramExecutor.constructTrace(ProgramExecutor.java:271)
	at microbat.codeanalysis.runtime.ProgramExecutor.run(ProgramExecutor.java:143)
	at tregression.TraceModelConstructor.constructTraceModel(TraceModelConstructor.java:64)
	at tregression.junit.TestCaseAnalyzer.runEvaluationForSingleTrial(TestCaseAnalyzer.java:393)
	at tregression.junit.TestCaseAnalyzer.runEvaluationForSingleTestCase(TestCaseAnalyzer.java:319)
	at tregression.junit.TestCaseAnalyzer.runEvaluation(TestCaseAnalyzer.java:243)
	at tregression.handler.EvaluationAllHandler$1.run(EvaluationAllHandler.java:54)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
test case has exception when generating trace:
Trial [testCaseName=org.apache.commons.math.util.OpenIntToDoubleHashMapTest#testPutKeysWithCollisions, mutatedFile=C:\microbat_evaluation_regression\apache-common-math-2.2\org.apache.commons.math.util.OpenIntToDoubleHashMap_355_21_2\OpenIntToDoubleHashMap.java, isBugFound=false, jumpSteps=null, totalSteps=0]

**Comment by llmhyy** [comment]
Personally, I think the bug is caused by a memory shortage to record the trace.
