### ISSUE TITLE
Record the Trace in Disk

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#33]
as titled.

**Comment by llmhyy** [comment]
Hi @lylytran  

would you please kindly check the following bug? The problem happens when I retrieves the regression of the 1st bug of closure project. thanks!

Caused by: sav.common.core.SavRtException: org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 64; Character reference "&#
	at microbat.handler.xml.VarValueXmlReader.read(VarValueXmlReader.java:62)
	at microbat.handler.xml.VarValueXmlReader.read(VarValueXmlReader.java:48)
	at tregression.io.RegressionRetriever.toVarValue(RegressionRetriever.java:328)
	at tregression.io.RegressionRetriever.loadSteps(RegressionRetriever.java:243)
	at tregression.io.RegressionRetriever.loadTrace(RegressionRetriever.java:135)
	at tregression.io.RegressionRetriever.retrieveRegressionInfo(RegressionRetriever.java:52)
	at tregression.io.RegressionRetriever.retriveRegression(RegressionRetriever.java:41)
	at tregression.handler.RegressionRetrieveHandler.execute(RegressionRetrieveHandler.java:47)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	... 38 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 64; Character reference "&#
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at microbat.handler.xml.VarValueXmlReader.read(VarValueXmlReader.java:58)
	... 52 more

**Comment by llmhyy** [comment]
hi @lylytran 

would you please also check the following bug? It happens for the 65th bug in Lang project.

Exception in thread "Thread-19" sav.common.core.SavRtException: javax.xml.transform.TransformerException: org.xml.sax.SAXException: Invalid UTF-16 surrogate detected: d842 ?
java.io.IOException: Invalid UTF-16 surrogate detected: d842 ?
	at microbat.handler.xml.VarValueXmlWriter.writeXml(VarValueXmlWriter.java:94)
	at microbat.handler.xml.VarValueXmlWriter.generateXmlContent(VarValueXmlWriter.java:69)
	at microbat.sql.TraceRecorder.generateXmlContent(TraceRecorder.java:102)
	at microbat.sql.TraceRecorder.insertSteps(TraceRecorder.java:92)
	at microbat.sql.TraceRecorder.insertTrace(TraceRecorder.java:68)
	at tregression.io.RegressionRecorder.record(RegressionRecorder.java:39)
	at tregression.empiricalstudy.TrialGenerator$DBRecording.run(TrialGenerator.java:298)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXException: Invalid UTF-16 surrogate detected: d842 ?
java.io.IOException: Invalid UTF-16 surrogate detected: d842 ?
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
	at microbat.handler.xml.VarValueXmlWriter.writeXml(VarValueXmlWriter.java:92)
	... 7 more
Caused by: org.xml.sax.SAXException: Invalid UTF-16 surrogate detected: d842 ?
java.io.IOException: Invalid UTF-16 surrogate detected: d842 ?
	at com.sun.org.apache.xml.internal.serializer.ToStream.characters(Unknown Source)
	at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.characters(Unknown Source)
	at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.characters(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(Unknown Source)
	... 10 more
Caused by: java.io.IOException: Invalid UTF-16 surrogate detected: d842 ?
	at com.sun.org.apache.xml.internal.serializer.ToStream.accumDefaultEscape(Unknown Source)
	at com.sun.org.apache.xml.internal.serializer.ToStream.processDirty(Unknown Source)
	... 20 more
