### ISSUE TITLE
DB Recording Exception

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/microbat#48]
hi @lylytran ,

It appears again. Probably, it happens for Lang-17

Exception in thread "Thread-17" sav.common.core.SavRtException: javax.xml.transform.TransformerException: org.xml.sax.SAXException: Invalid UTF-16 surrogate detected: d842 ?
java.io.IOException: Invalid UTF-16 surrogate detected: d842 ?
	at microbat.handler.xml.VarValueXmlWriter.writeXml(VarValueXmlWriter.java:94)
	at microbat.handler.xml.VarValueXmlWriter.generateXmlContent(VarValueXmlWriter.java:69)
	at microbat.sql.TraceRecorder.generateXmlContent(TraceRecorder.java:102)
	at microbat.sql.TraceRecorder.insertSteps(TraceRecorder.java:92)
	at microbat.sql.TraceRecorder.insertTrace(TraceRecorder.java:68)
	at tregression.io.RegressionRecorder.record(RegressionRecorder.java:39)
	at tregression.empiricalstudy.TrialGenerator$DBRecording.run(TrialGenerator.java:300)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXException: Invalid UTF-16 surrogate detected: d842 ?
java.io.IOException: Invalid UTF-16 surrogate detected: d842 ?
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
	at microbat.handler.xml.VarValueXmlWriter.writeXml(VarValueXmlWriter.java:92)
	... 7 more
Caused by: org.xml.sax.SAXException: Invalid UTF-16 surrogate detected: d842 ?
java.io.IOException: Invalid UTF-16 surrogate detected: d842 ?
	at com.sun.org.apache.xml.internal.serializer.ToStream.characters(Unknown Source)
	at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.characters(Unknown Source)
	at com.sun.org.apache.xml.internal.serializer.ToUnknownStream.characters(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(Unknown Source)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(Unknown Source)
	... 10 more
Caused by: java.io.IOException: Invalid UTF-16 surrogate detected: d842 ?
	at com.sun.org.apache.xml.internal.serializer.ToStream.accumDefaultEscape(Unknown Source)
	at com.sun.org.apache.xml.internal.serializer.ToStream.processDirty(Unknown Source)
	... 20 more

**Comment by llmhyy** [comment]
Lang-57
java.sql.BatchUpdateException: Data truncation: Data too long for column 'read_vars' at row 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
	at microbat.sql.TraceRecorder.insertSteps(TraceRecorder.java:95)
	at microbat.sql.TraceRecorder.insertTrace(TraceRecorder.java:68)
	at tregression.io.RegressionRecorder.record(RegressionRecorder.java:39)
	at tregression.empiricalstudy.TrialGenerator$DBRecording.run(TrialGenerator.java:300)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'read_vars' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
	... 7 more
java.sql.BatchUpdateException: Data truncation: Data too long for column 'read_vars' at row 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
	at microbat.sql.TraceRecorder.insertSteps(TraceRecorder.java:95)
	at microbat.sql.TraceRecorder.insertTrace(TraceRecorder.java:68)
	at tregression.io.RegressionRecorder.record(RegressionRecorder.java:39)
	at tregression.empiricalstudy.TrialGenerator$DBRecording.run(TrialGenerator.java:300)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'read_vars' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
	... 7 more
